language: python
python:
  - "3.7"
  - "3.8"
  - "pypy3"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest
deploy:
  - provider: releases
    edge: true
    token: $GITHUB_TOKEN
    on:
      branch: master
      tags: true
